### ISSUE TITLE
Problem to run on OpenBSD 5.1-current

### ISSUE THREAD

**Issue by jirib** [pbhenson/vSPC.py#2]
Problem to run on OpenBSD 5.1-current...

```
$ python2.7 ./vSPCServer -d 
ERROR:root:Top level exception caught
Traceback (most recent call last):
  File "./vSPCServer", line 138, in <module>
    vSPC(options.proxy_port, options.admin_port, options.vm_port_start, options.vm_expire_time, backend, options.ssl, options.cert, options.key).run()
  File "/tmp/isnotajoke-vSPC.py-9154df7/vSPC.py", line 1009, in __init__
    Poller.__init__(self)
  File "/tmp/isnotajoke-vSPC.py-9154df7/vSPC.py", line 501, in __init__
    self.epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'
```

```
$ sysctl kern.version                                                                                                                                                                                                                         
kern.version=OpenBSD 5.1-current (GENERIC.MP) #202: Thu Mar 15 18:33:09 MDT 2012
    deraadt@i386.openbsd.org:/usr/src/sys/arch/i386/compile/GENERIC.MP

$ python2.7 -V
Python 2.7.2
```

Strange, it works on Ubuntu Lucid (Python 2.6.5)? What my OpenBSD misses in python?

Thank you for help.
